FROM python:3.11-slim 
WORKDIR /code
COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir --upgrade -r /requirements.txt
EXPOSE 8080/tcp
COPY ./app /code/app
CMD ["fastapi", "run", "app/main.py", "--port", "8000"]





